name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to (e.g., staging, production)'
        required: true
        default: 'staging'
      local_directory:
        description: 'Directory to deploy from (e.g., build/ or dist/)'
        required: true
        default: 'build'
      s3_bucket:
        description: 'S3 Bucket name where files will be deployed'
        required: true
        default: 'your-default-bucket-name'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Choose the OS for your environment (can also use 'windows-latest' or 'macos-latest')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to the region of your S3 bucket

      - name: Sync files to S3
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          echo "Deploying from directory: ${{ github.event.inputs.local_directory }}"
          echo "Target S3 bucket: ${{ github.event.inputs.s3_bucket }}"
          
          # Sync the files to the specified S3 bucket
          aws s3 sync ./${{ github.event.inputs.local_directory }} s3://${{ github.event.inputs.s3_bucket }}/ --delete
